class AppStrings {
  static const Map<String, Map<String, String>> values = {
    'en': {
      'appTitle': 'Crypto & Metals Multi-Asset DCA Suite',
      'languageLabel': 'Lang:',
      'currencyLabel': 'Cur:',
      'liveMarketTitle': 'Live Market Rates (Crypto & Precious Metals)',
      'portfolioOverview': 'Total Consolidated Portfolio',
      'totalPortfolioInvested': 'Total Capital Invested',
      'activeTabsCount': 'Active Assets',
      'addAssetTab': 'Add Asset Tab',
      'deleteAssetTab': 'Delete Tab',
      'assetDropdownLabel': 'Select Asset / Commodity',
      'customAssetLabel': 'Enter Custom Asset Name',
      'customOption': 'Other (Custom)',
      'avgCostLabel': 'Average Cost per Unit',
      'totalInvested': 'Invested in Asset',
      'totalUnits': 'Total Units',
      'breakEvenLabel': 'Break-Even Price',
      'feeLabel': 'Trading Fee (%)',
      'buySteps': 'Purchase Tiers',
      'addStep': 'Add Tier',
      'calculate': 'Calculate',
      'priceLabel': 'Price',
      'amountLabel': 'Units',
      'totalLabel': 'Total',
      'tpTitle': 'Take-Profit Simulator',
      'tpSub': 'Scale out of your position with tiered targets',
      'tpStepPrice': 'Sell Price',
      'tpStepPercent': 'Sell %',
      'tpAddStep': 'Add Sell Tier',
      'tpAvgSellPrice': 'Avg Sell Price',
      'tpRealizedCash': 'Net Realized Cash',
      'tpRemaining': 'Remaining Position',
      'reverseDcaTitle': 'Reverse DCA: Target Average Calculator',
      'reverseDcaSub': 'Calculate units needed to reach target average price',
      'targetAvgPrice': 'Target Desired Average',
      'newBuyPrice': 'New Purchase Price',
      'reqUnits': 'Required Units',
      'reqCash': 'Required Additional Capital',
      'stopLossTitle': 'Risk Management: Stop-Loss Level',
      'stopLossSub': 'Set exit trigger to limit drawdown',
      'stopPriceLabel': 'Stop-Loss Price',
      'potentialLoss': 'Max Potential Loss',
      'savePortfolio': 'Save Portfolio',
      'savedPortfolios': 'Saved Portfolios',
      'portfolioNameHint': 'Portfolio Name',
      'saveSuccess': 'Portfolio saved successfully!',
      'exportPdf': 'Download PDF Report',
      'exportCsv': 'Download CSV (Excel)',
    },
    'tr': {
      'appTitle': 'Kripto & Emtia Çoklu DCA Portföyü',
      'languageLabel': 'Dil:',
      'currencyLabel': 'Birim:',
      'liveMarketTitle': 'Canlı Piyasa Fiyatları (Kripto & Değerli Metaller)',
      'portfolioOverview': 'Konsolide Portföy Toplamı',
      'totalPortfolioInvested': 'Toplam Yatırılan Anapara',
      'activeTabsCount': 'Aktif Varlıklar',
      'addAssetTab': 'Varlık Sekmesi Ekle',
      'deleteAssetTab': 'Sekmeyi Sil',
      'assetDropdownLabel': 'Varlık / Emtia Seçin',
      'customAssetLabel': 'Özel Varlık Adı Girin',
      'customOption': 'Diğer (Özel Giriş)',
      'avgCostLabel': 'Ortalama Birim Maliyetiniz',
      'totalInvested': 'Bu Varlıktaki Yatırım',
      'totalUnits': 'Toplam Adet',
      'breakEvenLabel': 'Başabaş (Break-Even) Fiyatı',
      'feeLabel': 'Komisyon / Makas (%)',
      'buySteps': 'Alım Kademeleri',
      'addStep': 'Kademe Ekle',
      'calculate': 'Hesapla',
      'priceLabel': 'Fiyat',
      'amountLabel': 'Adet',
      'totalLabel': 'Tutar',
      'tpTitle': 'Kademeli Satış (Take-Profit) Simülatörü',
      'tpSub': 'Pozisyonu parçalı kâr alarak realize edin',
      'tpStepPrice': 'Satış Fiyatı',
      'tpStepPercent': 'Satış %',
      'tpAddStep': 'Satış Kademesi Ekle',
      'tpAvgSellPrice': 'Ortalama Satış Fiyatı',
      'tpRealizedCash': 'Net Elde Edilen Nakit',
      'tpRemaining': 'Kalan Pozisyon',
      'reverseDcaTitle': 'Ters DCA: Hedef Maliyet İçin Ne Kadar Almalıyım?',
      'reverseDcaSub': 'Maliyetinizi düşürmek için gereken alım tutarını bulun',
      'targetAvgPrice': 'Hedef Ortalama Fiyat',
      'newBuyPrice': 'Yeni Alış Fiyatı',
      'reqUnits': 'Alınması Gereken Adet',
      'reqCash': 'Gereken Ek Bütçe',
      'stopLossTitle': 'Risk Yönetimi: Zarar Kes (Stop-Loss)',
      'stopLossSub': 'Maksimum katlanılabilir risk ve stop seviyesi',
      'stopPriceLabel': 'Stop-Loss Fiyatı',
      'potentialLoss': 'Olası Maksimum Zarar',
      'savePortfolio': 'Portföye Kaydet',
      'savedPortfolios': 'Kayıtlı Portföylerim',
      'portfolioNameHint': 'Portföy Adı (Örn: Sepetim)',
      'saveSuccess': 'Portföy başarıyla kaydedildi!',
      'exportPdf': 'PDF Raporu İndir',
      'exportCsv': 'Excel / CSV İndir',
    },
    'es': {
      'appTitle': 'Suite Multiactivo DCA Cripto y Metales',
      'languageLabel': 'Idioma:',
      'currencyLabel': 'Moneda:',
      'liveMarketTitle': 'Precios en Vivo (Cripto y Metales)',
      'portfolioOverview': 'Portafolio Consolidado Total',
      'totalPortfolioInvested': 'Capital Total Invertido',
      'activeTabsCount': 'Activos Activos',
      'addAssetTab': 'Añadir Pestaña',
      'deleteAssetTab': 'Eliminar Pestaña',
      'assetDropdownLabel': 'Seleccionar Activo',
      'customAssetLabel': 'Nombre Personalizado',
      'customOption': 'Otro (Personalizado)',
      'avgCostLabel': 'Costo Promedio por Unidad',
      'totalInvested': 'Inversión en Activo',
      'totalUnits': 'Unidades Totales',
      'breakEvenLabel': 'Precio de Equilibrio',
      'feeLabel': 'Comisión (%)',
      'buySteps': 'Niveles de Compra',
      'addStep': 'Añadir Nivel',
      'calculate': 'Calcular',
      'priceLabel': 'Precio',
      'amountLabel': 'Unidades',
      'totalLabel': 'Total',
      'tpTitle': 'Simulador Take-Profit',
      'tpSub': 'Salida escalonada con objetivos de beneficio',
      'tpStepPrice': 'Precio de Venta',
      'tpStepPercent': 'Venta %',
      'tpAddStep': 'Añadir Venta',
      'tpAvgSellPrice': 'Precio Medio de Venta',
      'tpRealizedCash': 'Efectivo Realizado Neto',
      'tpRemaining': 'Posición Restante',
      'reverseDcaTitle': 'DCA Inverso: Promedio Objetivo',
      'reverseDcaSub': 'Calcula unidades para alcanzar tu precio objetivo',
      'targetAvgPrice': 'Promedio Deseado',
      'newBuyPrice': 'Nuevo Precio de Compra',
      'reqUnits': 'Unidades Necesarias',
      'reqCash': 'Capital Adicional Necesario',
      'stopLossTitle': 'Gestión de Riesgo: Stop-Loss',
      'stopLossSub': 'Nivel de salida para limitar pérdidas',
      'stopPriceLabel': 'Precio Stop-Loss',
      'potentialLoss': 'Pérdida Máxima Potencial',
      'savePortfolio': 'Guardar Portafolio',
      'savedPortfolios': 'Portafolios Guardados',
      'portfolioNameHint': 'Nombre del Portafolio',
      'saveSuccess': '¡Portafolio guardado con éxito!',
      'exportPdf': 'Descargar Reporte PDF',
      'exportCsv': 'Descargar CSV (Excel)',
    },
    'de': {
      'appTitle': 'Krypto & Metalle Multi-Asset DCA Suite',
      'languageLabel': 'Sprache:',
      'currencyLabel': 'Währung:',
      'liveMarketTitle': 'Live-Marktkurse (Krypto & Edelmetalle)',
      'portfolioOverview': 'Konsolidiertes Gesamtportfolio',
      'totalPortfolioInvested': 'Gesamt investiertes Kapital',
      'activeTabsCount': 'Aktive Vermögenswerte',
      'addAssetTab': 'Reiter hinzufügen',
      'deleteAssetTab': 'Reiter löschen',
      'assetDropdownLabel': 'Anlage wählen',
      'customAssetLabel': 'Benutzerdefinierter Name',
      'customOption': 'Andere (Benutzerdefiniert)',
      'avgCostLabel': 'Durchschnittskosten pro Einheit',
      'totalInvested': 'Investition in Anlage',
      'totalUnits': 'Gesamteinheiten',
      'breakEvenLabel': 'Break-Even-Preis',
      'feeLabel': 'Handelsgebühr (%)',
      'buySteps': 'Kaufstufen',
      'addStep': 'Stufe hinzufügen',
      'calculate': 'Berechnen',
      'priceLabel': 'Preis',
      'amountLabel': 'Einheiten',
      'totalLabel': 'Gesamt',
      'tpTitle': 'Take-Profit-Simulator',
      'tpSub': 'Schrittweiser Ausstieg',
      'tpStepPrice': 'Verkaufspreis',
      'tpStepPercent': 'Verkauf %',
      'tpAddStep': 'Verkaufsstufe hinzufügen',
      'tpAvgSellPrice': 'Durchschnittl. Verkaufspreis',
      'tpRealizedCash': 'Realisierter Barwert',
      'tpRemaining': 'Verbleibende Position',
      'reverseDcaTitle': 'Umgekehrtes DCA: Ziel-Durchschnitt',
      'reverseDcaSub': 'Einheiten berechnen',
      'targetAvgPrice': 'Gewünschter Zielkurs',
      'newBuyPrice': 'Neuer Kaufpreis',
      'reqUnits': 'Erforderliche Einheiten',
      'reqCash': 'Erforderliches Zusatzkapital',
      'stopLossTitle': 'Risikomanagement: Stop-Loss',
      'stopLossSub': 'Ausstiegsschwelle zur Verlustbegrenzung',
      'stopPriceLabel': 'Stop-Loss-Preis',
      'potentialLoss': 'Maximaler Verlust',
      'savePortfolio': 'Portfolio speichern',
      'savedPortfolios': 'Gespeicherte Portfolios',
      'portfolioNameHint': 'Portfolio-Name',
      'saveSuccess': 'Portfolio erfolgreich gespeichert!',
      'exportPdf': 'PDF-Bericht herunterladen',
      'exportCsv': 'CSV herunterladen (Excel)',
    },
    'fr': {
      'appTitle': 'Suite Multi-Actifs DCA Crypto & Métaux',
      'languageLabel': 'Langue:',
      'currencyLabel': 'Devise:',
      'liveMarketTitle': 'Cours en Direct (Crypto & Métaux)',
      'portfolioOverview': 'Portefeuille Consolidé Global',
      'totalPortfolioInvested': 'Capital Total Investi',
      'activeTabsCount': 'Actifs Actifs',
      'addAssetTab': 'Ajouter Onglet',
      'deleteAssetTab': 'Supprimer Onglet',
      'assetDropdownLabel': 'Sélectionner l\'Actif',
      'customAssetLabel': 'Nom Personnalisé',
      'customOption': 'Autre (Personnalisé)',
      'avgCostLabel': 'Coût Moyen Unitaire',
      'totalInvested': 'Investi sur cet Actif',
      'totalUnits': 'Unités Totales',
      'breakEvenLabel': 'Prix d\'Équilibre',
      'feeLabel': 'Frais (%)',
      'buySteps': 'Paliers d\'Achat',
      'addStep': 'Ajouter Palier',
      'calculate': 'Calculer',
      'priceLabel': 'Prix',
      'amountLabel': 'Unités',
      'totalLabel': 'Total',
      'tpTitle': 'Simulateur Take-Profit',
      'tpSub': 'Sécurisez vos gains',
      'tpStepPrice': 'Prix de Vente',
      'tpStepPercent': 'Vente %',
      'tpAddStep': 'Ajouter Palier de Vente',
      'tpAvgSellPrice': 'Prix de Vente Moyen',
      'tpRealizedCash': 'Liquidités Réalisées',
      'tpRemaining': 'Position Restante',
      'reverseDcaTitle': 'DCA Inversé: Coût Moyen Cible',
      'reverseDcaSub': 'Unités requises',
      'targetAvgPrice': 'Prix Moyen Cible',
      'newBuyPrice': 'Nouveau Prix d\'Achat',
      'reqUnits': 'Unités Requises',
      'reqCash': 'Capital Supplémentaire Requis',
      'stopLossTitle': 'Gestion du Risque: Stop-Loss',
      'stopLossSub': 'Seuil de sortie pour limiter les pertes',
      'stopPriceLabel': 'Prix Stop-Loss',
      'potentialLoss': 'Perte Potentielle Maximale',
      'savePortfolio': 'Sauvegarder Portefeuille',
      'savedPortfolios': 'Portefeuilles Enregistrés',
      'portfolioNameHint': 'Nom du Portefeuille',
      'saveSuccess': 'Portefeuille enregistré avec succès !',
      'exportPdf': 'Télécharger le Rapport PDF',
      'exportCsv': 'Télécharger CSV (Excel)',
    },
    'it': {
      'appTitle': 'Suite Multi-Asset DCA Cripto e Metalli',
      'languageLabel': 'Lingua:',
      'currencyLabel': 'Valuta:',
      'liveMarketTitle': 'Prezzi in Tempo Reale (Cripto & Metalli)',
      'portfolioOverview': 'Portafoglio Consolidato Totale',
      'totalPortfolioInvested': 'Capitale Totale Investito',
      'activeTabsCount': 'Asset Attivi',
      'addAssetTab': 'Aggiungi Scheda',
      'deleteAssetTab': 'Elimina Scheda',
      'assetDropdownLabel': 'Seleziona Asset',
      'customAssetLabel': 'Nome Personalizzato',
      'customOption': 'Altro (Personalizzato)',
      'avgCostLabel': 'Costo Medio Unitario',
      'totalInvested': 'Investito in Questo Asset',
      'totalUnits': 'Unità Totali',
      'breakEvenLabel': 'Prezzo di Pareggio',
      'feeLabel': 'Commissione (%)',
      'buySteps': 'Scaglioni di Acquisto',
      'addStep': 'Aggiungi Scaglione',
      'calculate': 'Calcola',
      'priceLabel': 'Prezzo',
      'amountLabel': 'Unità',
      'totalLabel': 'Totale',
      'tpTitle': 'Simulatore Take-Profit',
      'tpSub': 'Prese di profitto graduali',
      'tpStepPrice': 'Prezzo di Vendita',
      'tpStepPercent': 'Vendita %',
      'tpAddStep': 'Aggiungi Vendita',
      'tpAvgSellPrice': 'Prezzo Medio di Vendita',
      'tpRealizedCash': 'Liquidità Realizzata Netta',
      'tpRemaining': 'Posizione Rimanente',
      'reverseDcaTitle': 'DCA Inverso: Media Obiettivo',
      'reverseDcaSub': 'Calcola le unità necessarie',
      'targetAvgPrice': 'Media Obiettivo Desiderata',
      'newBuyPrice': 'Nuovo Prezzo di Acquisto',
      'reqUnits': 'Unità Richieste',
      'reqCash': 'Capitale Aggiuntivo Richiesto',
      'stopLossTitle': 'Gestione del Rischio: Stop-Loss',
      'stopLossSub': 'Livello di uscita per contenere le perdite',
      'stopPriceLabel': 'Prezzo Stop-Loss',
      'potentialLoss': 'Perdita Massima Potenziale',
      'savePortfolio': 'Salva Portafoglio',
      'savedPortfolios': 'Portafogli Salvati',
      'portfolioNameHint': 'Nome Portafoglio',
      'saveSuccess': 'Portafoglio salvato con successo!',
      'exportPdf': 'Scarica Report PDF',
      'exportCsv': 'Scarica CSV (Excel)',
    },
    'ru': {
      'appTitle': 'Мульти-активный калькулятор DCA',
      'languageLabel': 'Язык:',
      'currencyLabel': 'Валюта:',
      'liveMarketTitle': 'Рыночные котировки онлайн (Крипто и Металлы)',
      'portfolioOverview': 'Общий портфель',
      'totalPortfolioInvested': 'Всего инвестировано',
      'activeTabsCount': 'Активные активы',
      'addAssetTab': 'Добавить вкладку',
      'deleteAssetTab': 'Удалить вкладку',
      'assetDropdownLabel': 'Выберите актив',
      'customAssetLabel': 'Пользовательский актив',
      'customOption': 'Другое (Вручную)',
      'avgCostLabel': 'Средняя цена покупки',
      'totalInvested': 'Инвестировано в актив',
      'totalUnits': 'Всего монет / единиц',
      'breakEvenLabel': 'Точка безубыточности',
      'feeLabel': 'Комиссия (%)',
      'buySteps': 'Уровни покупок',
      'addStep': 'Добавить уровень',
      'calculate': 'Рассчитать',
      'priceLabel': 'Цена',
      'amountLabel': 'Количество',
      'totalLabel': 'Сумма',
      'tpTitle': 'Симулятор Take-Profit',
      'tpSub': 'Частичная фиксация прибыли',
      'tpStepPrice': 'Цена продажи',
      'tpStepPercent': 'Продажа %',
      'tpAddStep': 'Добавить продажу',
      'tpAvgSellPrice': 'Средняя цена продажи',
      'tpRealizedCash': 'Чистый доход',
      'tpRemaining': 'Остаток позиции',
      'reverseDcaTitle': 'Обратный DCA: Расчет целевой цены',
      'reverseDcaSub': 'Сколько докупить',
      'targetAvgPrice': 'Желаемая средняя цена',
      'newBuyPrice': 'Новая цена покупки',
      'reqUnits': 'Требуемое количество',
      'reqCash': 'Необходимый капитал',
      'stopLossTitle': 'Управление рисками: Stop-Loss',
      'stopLossSub': 'Уровень выхода для ограничения убытков',
      'stopPriceLabel': 'Цена Stop-Loss',
      'potentialLoss': 'Максимальный убыток',
      'savePortfolio': 'Сохранить портфель',
      'savedPortfolios': 'Сохраненные портфели',
      'portfolioNameHint': 'Название портфеля',
      'saveSuccess': 'Портфель успешно сохранен!',
      'exportPdf': 'Скачать отчет PDF',
      'exportCsv': 'Скачать CSV (Excel)',
    }
  };

  static String tr(String lang, String key) {
    return values[lang]?[key] ?? values['en']?[key] ?? key;
  }
}
